spring:
  application:
    name: cassandra-app
  cassandra:
    local-datacenter: datacenter1
    contact-points: localhost
    port: 9042
    keyspace-name: imoveis
    schema-action: create_if_not_exists
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    serializer: org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          cassandra:
            core:
              cql:
                CqlTemplate: DEBUG